import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen">
        <h1 className="text-center text-3xl py-8">Welcome</h1>
        <section className="flex justify-around ">
          <div>
            <Link href="/Signin">Sign In</Link>
          </div>
          <div>
            <Link href="/Signup">Sign Up</Link>
          </div>
        </section>
      </div>
    </div>
  );
}
